version: "3.3"

services:
  
  react-prod:
    container_name: react-prod
    build:
      context: .
      dockerfile:
        prod/Dockerfile
    ports:
      - "3333:3000"
    networks:
      - devops-net 

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - react-prod
    networks:
      - devops-net 

networks:
  devops-net: