#the docker compose file version
version: "3.3"
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
  # service 1 named react-prod
  react-prod:
    container_name: react-prod
    build:
      context: .
      dockerfile:
        prod/Dockerfile
    ports:
      - "3333:80"
    networks:
      - devops-net 
      

networks:
  devops-net: