#the docker compose file version
version: "3.3"
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
  
  react-prod:
    container_name: react-prod
    build:
      context: .
      dockerfile:
        prod/Dockerfile
    ports:
      - "3333:3333"
    networks:
      - devops-net 

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - react-prod
    networks:
      - devops-net 

networks:
  devops-net: